[tool.black]
line-length = 79
preview = true

[tool.mypy]
plugins = "sqlmypy"
files = "ckan"
exclude = "ckan/(pastertemplates|tests|migration)"

[tool.towncrier]
filename = "CHANGELOG.rst"
directory = "changes"
package = "fpx"
package_dir = "."
issue_format = "{issue}"
title_format = "{version} ({project_date})"

[[tool.towncrier.type]]
directory = "migration"
name = "Migration guidelines"
showcontent = true

[[tool.towncrier.type]]
directory = "feature"
name = "New features"
showcontent = true


[[tool.towncrier.type]]
directory = "misc"
name = "Minor improvements"
showcontent = true

[[tool.towncrier.type]]
directory = "bug"
name = "Fixes"
showcontent = true


[[tool.towncrier.type]]
directory = "deprectation"
name = "Deprecations"
showcontent = true

[[tool.towncrier.type]]
directory = "removal"
name = "Removed functionality"
showcontent = true
