name: Tests
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        ckan-version: [3.7, 3.8, 3.9, "3.10"]
      fail-fast: false

    name: CKAN ${{ matrix.ckan-version }}
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Install requirements
      run: |
        pip install -e .
    - name: Run all tests
      run: pytest
